name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: cypress/relentlesshealthcypressautomation

      - name: Set up environment variables
        run: echo "${{ secrets.ENV_FILE }}" > .env
        working-directory: cypress/relentlesshealthcypressautomation

      - name: Run Cypress tests with Mochawesome reporter
        run: npx cypress run --spec "cypress/e2e/authUser/RH_authNavigation.cy.js" --browser chrome --headless
        working-directory: cypress/relentlesshealthcypressautomation

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/relentlesshealthcypressautomation/cypress/videos

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/relentlesshealthcypressautomation/cypress/screenshots

      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-report
          path: cypress/relentlesshealthcypressautomation/cypress/reports